# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-27 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AUD_MADdash',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('AUD', models.CharField(max_length=60, unique=True)),
                ('M1', models.IntegerField()),
                ('M5', models.IntegerField()),
                ('M15', models.IntegerField()),
                ('M30', models.IntegerField()),
                ('H1', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CAD_MADdash',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CAD', models.CharField(max_length=60, unique=True)),
                ('M1', models.IntegerField()),
                ('M5', models.IntegerField()),
                ('M15', models.IntegerField()),
                ('M30', models.IntegerField()),
                ('H1', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CHF_MADdash',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CHF', models.CharField(max_length=60, unique=True)),
                ('M1', models.IntegerField()),
                ('M5', models.IntegerField()),
                ('M15', models.IntegerField()),
                ('M30', models.IntegerField()),
                ('H1', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EUR_MADdash',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('EUR', models.CharField(max_length=60, unique=True)),
                ('M1', models.IntegerField()),
                ('M5', models.IntegerField()),
                ('M15', models.IntegerField()),
                ('M30', models.IntegerField()),
                ('H1', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GBP_MADdash',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('GBP', models.CharField(max_length=60, unique=True)),
                ('M1', models.IntegerField()),
                ('M5', models.IntegerField()),
                ('M15', models.IntegerField()),
                ('M30', models.IntegerField()),
                ('H1', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JPY_MADdash',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('JPY', models.CharField(max_length=60, unique=True)),
                ('M1', models.IntegerField()),
                ('M5', models.IntegerField()),
                ('M15', models.IntegerField()),
                ('M30', models.IntegerField()),
                ('H1', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NZD_MADdash',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NZD', models.CharField(max_length=60, unique=True)),
                ('M1', models.IntegerField()),
                ('M5', models.IntegerField()),
                ('M15', models.IntegerField()),
                ('M30', models.IntegerField()),
                ('H1', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='USD_MADdash',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('USD', models.CharField(max_length=60, unique=True)),
                ('M1', models.IntegerField()),
                ('M5', models.IntegerField()),
                ('M15', models.IntegerField()),
                ('M30', models.IntegerField()),
                ('H1', models.IntegerField()),
            ],
        ),
    ]
