# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_person_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='timestamp',
        ),
    ]
