# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_simple'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Simple',
        ),
    ]
