# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 12:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_person_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='qname',
            field=models.CharField(default=datetime.datetime(2016, 3, 21, 12, 33, 3, 719000, tzinfo=utc), max_length=120, verbose_name='qname'),
            preserve_default=False,
        ),
    ]
