# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 12:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_person_qname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='qname',
        ),
        migrations.RemoveField(
            model_name='person',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='person',
            name='Actual',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 21, 12, 44, 40, 946000, tzinfo=utc), max_length=120, verbose_name='Actual'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='Currency',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=120, verbose_name='Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='Detail',
            field=models.CharField(default=django.utils.timezone.now, max_length=120, verbose_name='Detail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='Forecast',
            field=models.CharField(default=datetime.datetime(2016, 3, 21, 12, 45, 6, 848000, tzinfo=utc), max_length=120, verbose_name='Forecast'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='Impact',
            field=models.CharField(default=datetime.datetime(2016, 3, 21, 12, 45, 11, 82000, tzinfo=utc), max_length=120, verbose_name='Impact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='Previous',
            field=models.CharField(default=datetime.datetime(2016, 3, 21, 12, 45, 13, 999000, tzinfo=utc), max_length=120, verbose_name='Previous'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='Time',
            field=models.CharField(default=datetime.datetime(2016, 3, 21, 12, 45, 16, 449000, tzinfo=utc), max_length=120, verbose_name='Time'),
            preserve_default=False,
        ),
    ]
