# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_auto_20160321_2056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EconomicReleases',
            new_name='EconomicRelease',
        ),
    ]
