# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_auto_20160321_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicrelease',
            name='Actual',
            field=models.CharField(max_length=60, verbose_name='Actual'),
        ),
        migrations.AlterField(
            model_name='economicrelease',
            name='Currency',
            field=models.CharField(max_length=60, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='economicrelease',
            name='Detail',
            field=models.CharField(max_length=60, verbose_name='Detail'),
        ),
        migrations.AlterField(
            model_name='economicrelease',
            name='Forecast',
            field=models.CharField(max_length=60, verbose_name='Forecast'),
        ),
        migrations.AlterField(
            model_name='economicrelease',
            name='Impact',
            field=models.CharField(max_length=60, verbose_name='Impact'),
        ),
        migrations.AlterField(
            model_name='economicrelease',
            name='Previous',
            field=models.CharField(max_length=60, verbose_name='Previous'),
        ),
        migrations.AlterField(
            model_name='economicrelease',
            name='Time',
            field=models.CharField(max_length=60, verbose_name='Time'),
        ),
    ]
