# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-01 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicReleases',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('EventID', models.CharField(max_length=60)),
                ('Delay', models.CharField(max_length=60)),
                ('EventCode', models.CharField(max_length=60)),
                ('CountryCode', models.CharField(max_length=60)),
                ('ReleasedOn', models.CharField(max_length=60)),
                ('EventName', models.CharField(max_length=60)),
                ('Values', models.CharField(max_length=500)),
                ('Consensus', models.CharField(max_length=60)),
                ('Actual', models.CharField(max_length=60)),
                ('Message', models.CharField(max_length=60)),
                ('Outcome', models.CharField(max_length=60)),
                ('Identity', models.CharField(max_length=60)),
            ],
        ),
    ]
